name: Run Selenium Tests

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]
  schedule:
    # Runs daily at 12:30 UTC (6:00 PM IST)
    - cron: '30 12 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Run tests with Maven
      run: mvn clean test -DsuiteXmlFile=testng.xml

    # Upload Surefire reports
    - name: Upload Surefire Reports
      uses: actions/upload-artifact@v4
      if: always()   # ensures upload even if tests fail
      with:
        name: surefire-reports
        path: target/surefire-reports

    # Upload ExtentReports (if generated)
    - name: Upload ExtentReports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: extent-reports
        path: target/extent-reports